api/src/lists/comments.service.spec.ts
api/src/lists/comments.service.ts
api/src/lists/dtos/create-comment.dto.ts
api/src/lists/dtos/update-comment.dto.ts
api/src/lists/lists.controller.ts
api/src/lists/lists.module.ts
api/src/lists/lists.service.ts
api/src/users/guards/comment-auth.guard.ts

Closes #32 
This PR adds a new `Comment` service that uses the comment-related code in the list module.
- Assert that using the comment-related endpoints work as expected.

feat(api): create comment service

---

api/src/lists/daos/list.dao.ts
api/src/lists/lists.service.ts

closes #34 
This MR makes some small changes in the list service and list dao to keep logic outside of dao. Not all the desired changes were applied, but we'll do more work on this once the bigger refactor is completed.
- Assert that the endpoints for get lists and toggle sharing a list work as expected.

refactor(api): use User service in list Service to avoid login in dao

---

api/.eslintrc.js
api/src/app.module.ts
api/src/lists/daos/list.dao.ts
api/src/lists/dtos/create-list-return.dto.ts
api/src/lists/guards/list.guard.ts
api/src/lists/lists.controller.ts
api/src/lists/lists.module.ts
api/src/lists/lists.service.ts
api/src/movies/dao/movies.dao.ts
api/src/movies/movies.controller.spec.ts
api/src/movies/movies.controller.ts
api/src/movies/movies.module.ts
api/src/movies/movies.service.spec.ts
api/src/movies/movies.service.ts
api/src/users/guards/comment-auth.guard.ts
api/src/users/users.module.ts

Closes #31
It creates a movies module using functionality taken from lists.

Implement Movies module

---

api/src/app.module.ts
api/src/image/image.module.ts
api/src/list/dao/list.dao.ts
api/src/list/dto/create-list.dto.ts
api/src/list/dto/update-list.dto.ts
api/src/list/guard/list-private.guard.ts
api/src/list/guard/share-list.guard.ts
api/src/list/list.controller.spec.ts
api/src/list/list.controller.ts
api/src/list/list.module.ts
api/src/list/list.service.spec.ts
api/src/list/list.service.ts
api/src/movie/dao/movie.dao.ts
api/src/movie/dto/update-movie-list.dto.ts
api/src/movie/movie.controller.ts
api/src/movie/movie.module.ts
api/src/movie/movie.service.ts
api/src/movielist/dto/create-movielist.dto.ts
api/src/movielist/movielist.controller.spec.ts
api/src/movielist/movielist.controller.ts
api/src/movielist/movielist.module.ts
api/src/movielist/movielist.service.spec.ts
api/src/movielist/movielist.service.ts
api/src/users/users.controller.spec.ts
api/src/users/users.controller.ts
api/src/users/users.module.ts

Closes #44
This PR creates the new `MovieList` module. All functions from list that uses the movies module have been relocated to this new module.
Run the app as normal and use the new `movielist - new` folder in postman for functionality testing.

Create `MovieList` module

---

api/src/movie/dao/movie.dao.ts
api/src/movie/dto/query.dto.ts
api/src/movie/movie.controller.ts
api/src/movie/movie.service.ts
api/src/sync/sync.service.ts

This PR fixes the issue with movie filters. Now it's possible to filter movies by `userId` and/or `listId` (fetching movies without filters would return the whole catalogue).

fix(api): solve issue with movie filters

---

api/src/list/guard/list-private.guard.ts
api/src/list/guard/share-list.guard.ts
api/src/list/list.controller.ts
api/src/list/list.service.ts
api/src/user/dao/user.dao.ts
api/src/user/dto/query.dto.ts
api/src/user/export/export.service.ts
api/src/user/user.controller.spec.ts
api/src/user/user.controller.ts
api/src/user/user.service.ts

Closes #41 
This PR adds filters in the user module to be able to get users by `id`, `username` and/or `email`. The original `getUser` method was not deleted since it provides a `findOrThrow` functionality that's useful in some scenarios.

feat(api): add filters for users

---

api/src/list/guard/list.guard.ts
api/src/movie/dto/movie.dto.ts
api/src/movie/movie.controller.ts
api/src/movielist/movielist.controller.ts
web/src/ambient.d.ts
web/src/hooks.server.ts
web/src/lib/List/ListTop.svelte
web/src/lib/List/UserModal.svelte
web/src/routes/+page.server.ts
web/src/routes/login/+page.server.ts
web/src/routes/signup/+page.server.ts
web/src/routes/user/lists/+page.server.ts

This PR modifies the FE to work with the refactored BE.
This is just a refactor to get it to work, we can do more in a follow-up PR to improve the implementation.
- Assert that all functionalities in FE work as expected.

refactor(web): modify the client to work with the refactored api

---

api/src/list/dao/list.dao.ts
api/src/list/dto/query.dto.ts
api/src/list/list.controller.ts
api/src/list/list.service.ts
api/src/movie/dao/movie.dao.ts
api/src/movielist/movielist.service.ts
api/src/user/dao/user.dao.ts
api/src/user/user.controller.spec.ts

Closes #28, #29
This PR adds pagination to `/lists/:id` (_get a specific list_) and `/lists` (_get all lists_).
Run the app as normal, verify functionality through the respective updated postman routes (_get a specific list_, _get all lists_)

Issue-28/29: Implement List pagination

---

web/src/lib/NewMovie/Delete.svelte
web/src/lib/NewMovie/Label.svelte
web/src/lib/NewMovie/Movie.svelte
web/src/lib/NewMovie/MovieContainer.svelte
web/src/lib/NewMovie/Watched.svelte

closes #67 
This PR adds a new movie component for the new design. This new movie component is very basic and will be completed once it's integrated in the movie page.
N/A

Closes #67: add new movie component

---

api/src/comment/dao/comment.dao.ts
api/src/list/list.controller.ts
api/src/list/list.service.ts
api/src/movie/dao/movie.dao.ts
api/src/user/dao/user.dao.ts
api/src/user/user.controller.ts
api/src/user/user.service.ts

Closes #71 
This PR adds various aggregate functions required by the (yet nonexistent) user page.
A new route has been added to postman for user stats testing:
- `get user stats`: `{{BASE_URL}}/users/:id/stats`

feat(api): implement aggregate functions

---

api/src/list/dto/list.dto.ts
web/src/ambient.d.ts
web/src/lib/Image.svelte
web/src/lib/List/ListsContainer.svelte
web/src/lib/MainContainer.svelte
web/src/lib/Nav/Link.svelte
web/src/lib/Nav/Nav.svelte
web/src/routes/user/lists/+page.server.ts
web/src/routes/user/lists/+page.svelte
web/src/utils/consts.ts

This PR improves the responsiveness of the landing page, and uses the new improvements in the api to get shared lists and paginate results.

refactor(web): improve landing page's responsiveness

---

web/package.json
web/src/ambient.d.ts
web/src/lib/Toast/Toast.svelte
web/src/lib/Toast/Toasts.svelte
web/src/routes/login/+page.server.ts
web/src/routes/login/+page.svelte
web/src/routes/login/messages.ts
web/src/routes/user/lists/+page.server.ts
web/src/store/index.ts
web/src/store/toast.ts
web/tailwind.config.js

closes #4 
This PR adds a toast component, and uses it in the login page. Also, it modifies the landing page to handle the recent changes in the backend (#84).
- Assert that using a wrong email or password in the login page triggers a toast with correct feedback.

closes #4: add toast component

---

api/src/sync/sync.service.ts

closes #91 
This PR grabs all movies from the db (using same logic as done in [movielist](https://github.com/funnls/cinesync/pull/87/files) service) and sends them all to be updated by the sync service.
Run the app as normal (optionally changing `CronExpression.EVERY_HOUR` to `CronExpression.EVERY_5_SECONDS` for easier testing) and assert that each movie has been updated after the service finishes its refresh job.

Fix: Sync service fails to update all movies in db

---

web/src/lib/Image.svelte
web/src/lib/List/ListsContainer.svelte
web/src/lib/Movie/Container.svelte
web/src/lib/Movie/Delete.svelte
web/src/lib/Movie/Movie.svelte
web/src/lib/Movie/MovieContainer.svelte
web/src/lib/Movie/Watched.svelte
web/src/lib/Movie/messages.ts
web/src/routes/user/lists/+page.svelte
web/src/routes/user/lists/[slug]/+page.server.ts
web/src/routes/user/lists/[slug]/+page.svelte

Progress towards #98 
This PR adds functionality for the `watch` and `delete` buttons in the list page.
**Note**
Issue #98 will be addressed with multiple PRs.
- Assert that the `watch` and `delete` buttons for movies in the list page work as expected.

refactor(web): integrate watched and delete for movies

---

api/src/auth/auth.controller.ts
web/src/routes/signup/+page.server.ts
web/src/routes/signup/+page.svelte
web/src/routes/signup/messages.ts

This PR adds using recent changes to the `auth` module for signup.
- Assert that successful and unsuccessful signup work as expected.

fix: use auth module for signup

---

web/src/lib/List/ListNameModal.svelte
web/src/lib/Title.svelte
web/src/lib/TopSection.svelte
web/src/routes/user/lists/+page.svelte
web/src/routes/user/lists/[slug]/+page.server.ts
web/src/routes/user/lists/[slug]/+page.svelte

closes #104 
This PR adds the ability to rename a list.
- Run the FE (with local or prod backend)
- Assert that the name editing feature works as expected.

feat(web): add renaming a list

---

web/src/lib/List/Delete.svelte
web/src/lib/List/ListNameModal.svelte
web/src/lib/List/ListShareModal.svelte
web/src/lib/List/messages.ts
web/src/lib/Modal.svelte
web/src/lib/Movie/Delete.svelte
web/src/lib/Movie/Movie.svelte
web/src/lib/Movie/MovieModal.svelte
web/src/lib/Movie/MovieResult.svelte
web/src/lib/Movie/Watched.svelte
web/src/lib/Movie/messages.ts
web/src/routes/user/lists/+page.server.ts
web/src/routes/user/lists/[slug]/+page.server.ts
web/src/routes/user/lists/[slug]/+page.svelte
web/src/routes/user/profile/+page.svelte

This PR improves the way we rerender afterany CRUD operation related to lists/movies.
- Run the webapp
- Assert that all adding/editing/deleting features related to movies and lists work as expected.

feat(web): improve rerendering after crud operation

---

api/.vscode/launch.json
api/eslint.config.mjs
api/src/app.module.ts
api/src/movie/movie.service.ts
api/src/prisma/prisma.service.ts
api/src/search/dao/movie.dao.ts
api/src/search/dao/tmdb.dao.ts
api/src/search/dto/query.dto.ts
api/src/search/dto/search.dto.ts
api/src/search/search.controller.spec.ts
api/src/search/search.controller.ts
api/src/search/search.module.ts
api/src/search/search.service.spec.ts
api/src/search/search.service.ts
api/src/utils/apiURLs.ts
api/src/utils/index.ts
api/src/utils/mappers.ts

closes #35 
This PR adds a search service in the backend that combines `db` search and `tmdb` search.
Cache has been added to the search service, but not fully integrated with the rest of the backend. It'll be completed in a followup PR (along with more cache features).
- Run the backend
- Assert that the `/search` endpoint returns both `db` and `tmdb` results that are appropriate for the term used for the search.

feat(api): add search

---

api/package-lock.json
api/package.json
api/src/comment/comment.module.ts
api/src/comment/comment.service.ts
api/src/comment/dao/comment.dao.ts
api/src/comment/dto/comment.dto.ts
api/src/comment/guard/comment-auth.guard.ts
api/src/config/redisCache.ts
api/src/list/list.controller.ts
api/src/list/list.service.ts

Ths PR fixes the issue with comments in the BE, and it also adds a change to the library used to add `redis` to the cache manager.

fix(api): comments not working and modifying cache tool

---

web/package-lock.json
web/package.json
web/src/ambient.d.ts
web/src/lib/Comment/Comment.svelte
web/src/lib/Comment/messages.ts
web/src/routes/user/lists/[slug]/+page.server.ts
web/src/routes/user/lists/[slug]/+page.svelte

This PR adds comments for a single list.
- Assert that comments can be read and posted via list page.

feat(web): add comments
